### ISSUE TITLE
qt backend issue in windows 10

### ISSUE THREAD

**Issue by boazmohar** [sanderslab/magellanmapper#428]
Hi,

Just tried installing from windows 10 using both the `.yml` file and conda and the `.txt` with pip.
In both I had an issue with compilation of mayvi that I could solve by pip installing it seperatly.
However (and I don't know if thoes are related), when I try to open the GUI or do the registration I get the following error:
```bash
 File "C:\Users\moharb\Miniconda3\envs\mag\lib\site-packages\traitsui\toolkit.py", line 39, in assert_toolkit_import
    raise RuntimeError(
RuntimeError: Importing from qt4 backend after selecting null backend!
```
<details>
    <summary> full output </summary>

```bash
   (mag) U:\>python U:\magellanmapper\run.py --img "E:\Dropbox (HHMI)\Projects\Unbised\CCF_tools\iDISCO_template_flipped_resized(456,528,320)_image5d.npy" "E:\Dropbox (HHMI)\Projects\Unbised\CCF_tools\" --register --atlas_profile abaccfv3 -v
Starting MagellanMapper run script...
magmap.settings.profiles - INFO - Loaded profile from 'C:\Users\moharb\AppData\Local\MagellanMapper\prefs.yaml':
{'fig_save_dir': '', 'import_dir': '', 'roi_circles': '', 'roi_plane': '', 'roi_styles': '', 'settings_name': 'default'}
magmap.io.cli - INFO - Launched MagellanMapper from U:\magellanmapper\run.py
root - INFO - Set filenames to ['E:\\Dropbox (HHMI)\\Projects\\Unbised\\CCF_tools\\iDISCO_template_flipped_resized(456,528,320)_image5d.npy', 'E:\\Dropbox (HHMI)\\Projects\\Unbised\\CCF_tools" --register --atlas_profile abaccfv3 -v'], current filename E:\Dropbox (HHMI)\Projects\Unbised\CCF_tools\iDISCO_template_flipped_resized(456,528,320)_image5d.npy
magmap.io.cli - INFO - Set default (channel 0) ROI profile: default
magmap.io.cli - INFO - Set atlas profile to default
root - INFO - set multiprocessing start method to spawn
root - INFO - Loading main image
magmap.io.importer - INFO - Image filename: E:\Dropbox (HHMI)\Projects\Unbised\CCF_tools\iDISCO_template_flipped_resized(456,528,320).
Converted to base filename: E:\Dropbox (HHMI)\Projects\Unbised\CCF_tools\iDISCO_template_flipped_resized(456,528,320)
root - INFO - Reading image metadata from E:\Dropbox (HHMI)\Projects\Unbised\CCF_tools\iDISCO_template_flipped_resized(456,528,320)_meta.yml
root - INFO - loaded image5d version number 15
root - INFO - names: ['iDISCO_template_flipped']
root - INFO - sizes [[1, 320, 528, 456]]
root - INFO - set resolutions to [[1440.625       612.35477902 1363.20531057]]
root - INFO - magnification: 1
root - INFO - zoom: 1
root - INFO - set near_min to [0.0]
root - INFO - set near_max to [0.002883254492147953]
root - INFO - Set vmax_overview to [0.00317158]
root - INFO - image5d shape: (1, 320, 528, 456)
pyface.base_toolkit - INFO - Could not load pyface.toolkits plugin 'qt4' from 'pyface.ui.qt4.init'
pyface.base_toolkit - INFO - Could not load pyface.toolkits plugin 'wx' from 'pyface.ui.wx.init'
pyface.base_toolkit - INFO - Could not load pyface.toolkits plugin 'qt' from 'pyface.ui.qt4.init'
root - CRITICAL - Unhandled exception. Additional log saved to: C:\Users\moharb\AppData\Local\Temp\magellanmapper_error_usz0eolv.log
Traceback (most recent call last):
  File "U:\magellanmapper\run.py", line 23, in <module>
    load_env.main()
  File "U:\magellanmapper\magmap\io\load_env.py", line 185, in main
    launch_magmap()
  File "U:\magellanmapper\magmap\io\load_env.py", line 139, in launch_magmap
    from magmap.gui import visualizer
  File "U:\magellanmapper\magmap\gui\visualizer.py", line 53, in <module>
    from traitsui.qt4.editor import Editor
  File "C:\Users\moharb\Miniconda3\envs\mag\lib\site-packages\traitsui\qt4\__init__.py", line 35, in <module>
    from . import toolkit
  File "C:\Users\moharb\Miniconda3\envs\mag\lib\site-packages\traitsui\qt4\toolkit.py", line 30, in <module>
    assert_toolkit_import(["qt4", "qt"])
  File "C:\Users\moharb\Miniconda3\envs\mag\lib\site-packages\traitsui\toolkit.py", line 39, in assert_toolkit_import
    raise RuntimeError(
RuntimeError: Importing from qt4 backend after selecting null backend!
```
</details>

If I set:
```bash
(mag) U:\>set QT_API=pyqt5

(mag) U:\>set ETS_TOOLKIT=pyqt
```

I get a different error:
```bash
File "C:\Users\moharb\Miniconda3\envs\mag\lib\site-packages\pyface\base_toolkit.py", line 207, in import_toolkit
    raise RuntimeError(msg)
RuntimeError: No pyface.toolkits plugin found for toolkit pyqt
```

<details>
    <summary> full output </summary>

```
(mag) U:\>python U:\magellanmapper\run.py --img "E:\Dropbox (HHMI)\Projects\Unbised\CCF_tools\iDISCO_template_flipped_resized(456,528,320)_image5d.npy" "E:\Dropbox (HHMI)\Projects\Unbised\CCF_tools\" --register --atlas_profile abaccfv3 -v
Starting MagellanMapper run script...
magmap.settings.profiles - INFO - Loaded profile from 'C:\Users\moharb\AppData\Local\MagellanMapper\prefs.yaml':
{'fig_save_dir': '', 'import_dir': '', 'roi_circles': '', 'roi_plane': '', 'roi_styles': '', 'settings_name': 'default'}
magmap.io.cli - INFO - Launched MagellanMapper from U:\magellanmapper\run.py
root - INFO - Set filenames to ['E:\\Dropbox (HHMI)\\Projects\\Unbised\\CCF_tools\\iDISCO_template_flipped_resized(456,528,320)_image5d.npy', 'E:\\Dropbox (HHMI)\\Projects\\Unbised\\CCF_tools" --register --atlas_profile abaccfv3 -v'], current filename E:\Dropbox (HHMI)\Projects\Unbised\CCF_tools\iDISCO_template_flipped_resized(456,528,320)_image5d.npy
magmap.io.cli - INFO - Set default (channel 0) ROI profile: default
magmap.io.cli - INFO - Set atlas profile to default
root - INFO - set multiprocessing start method to spawn
root - INFO - Loading main image
magmap.io.importer - INFO - Image filename: E:\Dropbox (HHMI)\Projects\Unbised\CCF_tools\iDISCO_template_flipped_resized(456,528,320).
Converted to base filename: E:\Dropbox (HHMI)\Projects\Unbised\CCF_tools\iDISCO_template_flipped_resized(456,528,320)
root - INFO - Reading image metadata from E:\Dropbox (HHMI)\Projects\Unbised\CCF_tools\iDISCO_template_flipped_resized(456,528,320)_meta.yml
root - INFO - loaded image5d version number 15
root - INFO - names: ['iDISCO_template_flipped']
root - INFO - sizes [[1, 320, 528, 456]]
root - INFO - set resolutions to [[1440.625       612.35477902 1363.20531057]]
root - INFO - magnification: 1
root - INFO - zoom: 1
root - INFO - set near_min to [0.0]
root - INFO - set near_max to [0.002883254492147953]
root - INFO - Set vmax_overview to [0.00317158]
root - INFO - image5d shape: (1, 320, 528, 456)
root - CRITICAL - Unhandled exception. Additional log saved to: C:\Users\moharb\AppData\Local\Temp\magellanmapper_error_tge6gjph.log
Traceback (most recent call last):
  File "U:\magellanmapper\run.py", line 23, in <module>
    load_env.main()
  File "U:\magellanmapper\magmap\io\load_env.py", line 185, in main
    launch_magmap()
  File "U:\magellanmapper\magmap\io\load_env.py", line 139, in launch_magmap
    from magmap.gui import visualizer
  File "U:\magellanmapper\magmap\gui\visualizer.py", line 43, in <module>
    from pyface import confirmation_dialog
  File "C:\Users\moharb\Miniconda3\envs\mag\lib\site-packages\pyface\confirmation_dialog.py", line 15, in <module>
    from .toolkit import toolkit_object
  File "C:\Users\moharb\Miniconda3\envs\mag\lib\site-packages\pyface\toolkit.py", line 23, in <module>
    toolkit = toolkit_object = find_toolkit("pyface.toolkits")
  File "C:\Users\moharb\Miniconda3\envs\mag\lib\site-packages\pyface\base_toolkit.py", line 263, in find_toolkit
    return import_toolkit(ETSConfig.toolkit, entry_point)
  File "C:\Users\moharb\Miniconda3\envs\mag\lib\site-packages\pyface\base_toolkit.py", line 207, in import_toolkit
    raise RuntimeError(msg)
RuntimeError: No pyface.toolkits plugin found for toolkit pyqt
```

</details>

Any ideas what I should do?

<details>
    <summary> Env info</summary>

python:
```bash
Python 3.8.15 | packaged by conda-forge | (default, Jan 26 2023, 10:42:30) [MSC v.1929 64 bit (AMD64)] on win32
```
pip list:
```
appdirs==1.4.4
apptools==5.2.0
bg-atlasapi @ https://github.com/brainglobe/bg-atlasapi/archive/refs/heads/master.zip
bg-space==0.6.0
boto3==1.26.60
botocore==1.29.60
bump2version==1.0.1
bumpversion==0.6.0
certifi==2022.12.7
charset-normalizer==3.0.1
click==8.1.3
colorama==0.4.6
configobj==5.0.8
contourpy==1.0.7
cycler==0.11.0
envisage==6.1.0
fonttools==4.38.0
future==0.18.3
idna==3.4
imagecodecs==2023.1.23
imageio==2.25.0
importlib-resources==5.10.2
javabridge==1.0.19.post4+gbebed64
jmespath==1.0.1
kiwisolver==1.4.4
magellanmapper==1.6a2
markdown-it-py==2.1.0
matplotlib==3.6.3
matplotlib-scalebar==0.8.1
mayavi==4.8.1
mdurl==0.1.2
meshio==5.3.4
networkx==3.0
numpy==1.24.1
packaging==23.0
pandas==1.5.3
Pillow==9.4.0
pyamg==4.2.3
pyface==7.4.2
Pygments==2.14.0
pyparsing==3.0.9
PyQt5==5.15.8
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.1
python-bioformats==4.0.5.post2+g51eb88a
python-dateutil==2.8.2
pytz==2022.7.1
PyWavelets==1.4.1
PyYAML==6.0
requests==2.28.2
rich==13.3.1
s3transfer==0.6.0
scikit-image==0.19.3
scipy==1.10.0
SimpleITK==2.0.2rc2.dev785+g8ac4f
six==1.16.0
tifffile==2023.1.23.1
traits==6.4.1
traitsui==7.4.1
treelib==1.6.1
typing_extensions==4.4.0
urllib3==1.26.14
vtk==9.2.5
zipp==3.12.0
```
</details>

**Comment by yoda-vid** [comment]
Thanks for pointing this out and the detailed report! I can reproduce it as well, on both Windows and macOS.

Looks like a workaround is to downgrade PyQt5 from v5.15.8 to v5.15.7:

```
pip install PyQt5==5.15.7
```

Let me know if this works for you.

> In both I had an issue with compilation of mayvi that I could solve by pip installing it seperatly.

Thanks also for mentioning this. Sounds like this may be a workaround for the issue I was encountering in #401.

**Comment by boazmohar** [comment]
Hi @yoda-vid, 

This has solved it for me. Not sure if to close the issue myself, but fell free to do so.

Thanks for the quick fix!
Boaz

**Comment by yoda-vid** [comment]
Thanks @boazmohar, glad it worked for you! Let me know if anything else comes up.
