### ISSUE TITLE
Error when setting up custom colormaps in Matplotlib >= 3.8

### ISSUE THREAD

**Issue by yoda-vid** [sanderslab/magellanmapper#558]
Setting up custom linear segmented colormaps in Matplotlib v3.8 leads to an error that the color is not found:

```
Traceback (most recent call last):
  File "/opt/magellanmapper/magmap/gui/event_handlers.py", line 55, in eventFilter
    self.fn_open_image(url)
  File "/opt/magellanmapper/magmap/gui/visualizer.py", line 2208, in open_image
    self.update_filename(filename)
  File "/opt/magellanmapper/magmap/gui/visualizer.py", line 2187, in update_filename
    self._filename = filename
  File "/opt/venvs/vmag6/lib/python3.9/site-packages/traits/trait_notifiers.py", line 478, in __call__
    self.notify_listener(self, object, trait_name, old, new)
  File "/opt/venvs/vmag6/lib/python3.9/site-packages/traits/trait_notifiers.py", line 552, in _notify_method_listener
    self._dispatch_change_event(
  File "/opt/venvs/vmag6/lib/python3.9/site-packages/traits/trait_notifiers.py", line 532, in _dispatch_change_event
    handle_exception(object, trait_name, old, new)
  File "/opt/venvs/vmag6/lib/python3.9/site-packages/traits/trait_notifiers.py", line 149, in _handle_exception
    raise excp
  File "/opt/venvs/vmag6/lib/python3.9/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/opt/venvs/vmag6/lib/python3.9/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/opt/magellanmapper/magmap/gui/visualizer.py", line 2251, in _image_path_updated
    np_io.setup_images(
  File "/opt/magellanmapper/magmap/io/np_io.py", line 523, in setup_images
    colormaps.setup_cmaps()
  File "/opt/magellanmapper/magmap/plot/colormaps.py", line 45, in setup_cmaps
    CMAPS[config.Cmaps.CMAP_GRBK_NAME] = make_dark_linear_cmap(
  File "/opt/magellanmapper/magmap/plot/colormaps.py", line 40, in make_dark_linear_cmap
    return colors.LinearSegmentedColormap.from_list(name, ("black", color))
  File "/opt/venvs/vmag6/lib/python3.9/site-packages/matplotlib/colors.py", line 1065, in from_list
    r, g, b, a = to_rgba_array(colors).T
  File "/opt/venvs/vmag6/lib/python3.9/site-packages/matplotlib/colors.py", line 489, in to_rgba_array
    raise ValueError(f"{c!r} is not a valid color value.")
ValueError: 'black' is not a valid color value.
```

**Comment by yoda-vid** [comment]
Fixed by #559.
