### ISSUE TITLE
GUI not starting anymore in new version

### ISSUE THREAD

**Issue by SaibotMagd** [sanderslab/magellanmapper#86]
Sorry I worked only with the CLI for most of the time, but today I started to work on the cell-counting and now I can start the GUI anymore:
"
python run.py
Starting MagellanMapper run script...
magmap.io.cli - INFO - Launched MagellanMapper from run.py
magmap.io.cli - INFO - Set default (channel 0) ROI profile: default
magmap.io.cli - INFO - Set atlas profile to default
root - INFO - setting up Matplotlib style default
root - INFO - applying theme DEFAULT
root - INFO - Loaded database from /home/.local/share/MagellanMapper/magmap.db
root - INFO - set multiprocessing start method to fork
root - INFO - No image filename set for processing files, skipping
root - ERROR - /home/anaconda3/envs/mag/lib/python3.6/site-packages/traits/observation/_has_traits_helpers.py:83: RuntimeWarning: Trait '_wrappers' (trait type: List) on class ActionItem is defined with comparison_mode=<ComparisonMode.equality: 2>. Mutations and extended traits cannot be observed if a new container compared equally to the old one is set. Redefine the trait with List(..., comparison_mode=<ComparisonMode.identity: 1>) to avoid this.
  RuntimeWarning,
root - ERROR - /home/anaconda3/envs/mag/lib/python3.6/site-packages/traits/observation/_has_traits_helpers.py:83: RuntimeWarning: Trait 'adapters' (trait type: List) on class SegmentsArrayAdapter is defined with comparison_mode=<ComparisonMode.equality: 2>. Mutations and extended traits cannot be observed if a new container compared equally to the old one is set. Redefine the trait with List(..., comparison_mode=<ComparisonMode.identity: 1>) to avoid this.
  RuntimeWarning,
root - ERROR - /home/anaconda3/envs/mag/lib/python3.6/site-packages/traits/observation/_has_traits_helpers.py:83: RuntimeWarning: Trait 'adapters' (trait type: List) on class ProfilesArrayAdapter is defined with comparison_mode=<ComparisonMode.equality: 2>. Mutations and extended traits cannot be observed if a new container compared equally to the old one is set. Redefine the trait with List(..., comparison_mode=<ComparisonMode.identity: 1>) to avoid this.
  RuntimeWarning,
root - ERROR - /home/anaconda3/envs/mag/lib/python3.6/site-packages/traits/observation/_has_traits_helpers.py:83: RuntimeWarning: Trait 'adapters' (trait type: List) on class ImportFilesArrayAdapter is defined with comparison_mode=<ComparisonMode.equality: 2>. Mutations and extended traits cannot be observed if a new container compared equally to the old one is set. Redefine the trait with List(..., comparison_mode=<ComparisonMode.identity: 1>) to avoid this.
  RuntimeWarning,
root - INFO - set border to zeros
root - INFO - set border to [0. 0. 0.]
root - CRITICAL - Unhandled exception. Additional log saved to: /tmp/magellanmapper_error_45tywcdt.log
Traceback (most recent call last):
  File "run.py", line 237, in <module>
    main()
  File "run.py", line 170, in main
    launch_magmap()
  File "run.py", line 128, in launch_magmap
    visualizer.main()
  File "/home/toolboxes/magellanmapper/magmap/gui/visualizer.py", line 85, in main
    visualization = Visualization()
  File "/home/toolboxes/magellanmapper/magmap/gui/visualizer.py", line 832, in __init__
    self._profiles_ver = libmag.get_version(True)
  File "/home/toolboxes/magellanmapper/magmap/io/libmag.py", line 1212, in get_version
    ver = metadata.version(config.APP_NAME.lower())
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 861, in version
    return distribution(distribution_name).version
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 834, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/anaconda3/envs/mag/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 449, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for magellanmapper
"

I'm importing the datafile using an old version of mag and then try to start the GUI by loading the dataset. Maybe this will work

**Comment by yoda-vid** [comment]
Thanks for reporting this! Glad you are trying the GUI for cell counting and hope I can help.

> File "/home/toolboxes/magellanmapper/magmap/io/libmag.py", line 1212, in get_version
ver = metadata.version(config.APP_NAME.lower())

I was getting this error as well and just recently fixed it in commit 99294555e0d6dbbbd40030ffc942d895a52f5573. If you update mag on git (eg `git checkout master; git pull`), does it fix the GUI error for you?

> root - ERROR - /home/anaconda3/envs/mag/lib/python3.6/site-packages/traits/observation/_has_traits_helpers.py:83: RuntimeWarning: Trait '_wrappers' (trait type: List) on class ActionItem is defined with comparison_mode=<ComparisonMode.equality: 2>. Mutations and extended traits cannot be observed if a new container compared equally to the old one is set. Redefine the trait with List(..., comparison_mode=<ComparisonMode.identity: 1>) to avoid this.

Hm I haven't seen these errors before, not sure if they're also causing the GUI issue or coincidental. Would you mind posting the output of `conda list` to see what version of Traits is installed? I'm hoping the above update will fix at least the GUI start.

**Comment by SaibotMagd** [comment]
Thx this worked.

Anyhow I'm using this conda setup:

"
```
# packages in environment at /home/anaconda3/envs/mag:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
aiocontextvars            0.2.2                      py_0    conda-forge
alabaster                 0.7.12                   py36_0  
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
apptools                  4.5.0              pyh9f0ad1d_1    conda-forge
argh                      0.26.2                   py36_0  
arrow                     0.13.1                   py36_0  
astroid                   2.5              py36h06a4308_1  
async_generator           1.10             py36h28b3542_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
autopep8                  1.5.6              pyhd3eb1b0_0  
awscli                    1.18.203         py36h5fab9bb_0    conda-forge
babel                     2.9.0              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     19.10b0                    py_0  
bleach                    3.3.0              pyhd3eb1b0_0  
blosc                     1.21.0               h9c3ff4c_0    conda-forge
boto3                     1.16.43            pyhd8ed1ab_0    conda-forge
botocore                  1.19.43            pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                he1b5a44_3    conda-forge
brotlipy                  0.7.0           py36he6145b8_1001    conda-forge
brunsli                   0.1                  h9c3ff4c_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cairo                     1.16.0            h9f066cc_1006    conda-forge
certifi                   2021.5.30        py36h5fab9bb_0    conda-forge
cffi                      1.14.4           py36hc120d54_1    conda-forge
chardet                   4.0.0           py36h06a4308_1003  
charls                    2.1.0                h9c3ff4c_2    conda-forge
click                     7.1.2              pyhd3eb1b0_0  
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
contextvars               2.4                        py_0    conda-forge
cookiecutter              1.7.2              pyhd3eb1b0_0  
cryptography              3.3.1            py36h0a59100_0    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.24          py36hc4f0c31_0    conda-forge
cytoolz                   0.11.0           py36h1d69622_1    conda-forge
dask-core                 2020.12.0          pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713                   py_0  
docutils                  0.15.2           py36h5fab9bb_1    conda-forge
double-conversion         3.1.5                he1b5a44_2    conda-forge
eigen                     3.3.9                h4bd325d_1    conda-forge
entrypoints               0.3                      py36_0  
enum34                    1.1.10           py36h9f0ad1d_2    conda-forge
envisage                  4.9.2              pyh9f0ad1d_1    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
ffmpeg                    4.3.1                h3215721_1    conda-forge
flake8                    3.9.0              pyhd3eb1b0_0  
fontconfig                2.13.1            h7e3eb15_1002    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
future                    0.18.2                   py36_1  
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
gl2ps                     1.4.2                h0708190_0    conda-forge
glew                      2.1.0                h9c3ff4c_2    conda-forge
glib                      2.66.4               hcd2ae1e_1    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.18.2               h3560a44_1    conda-forge
harfbuzz                  2.7.2                ha5b49bf_1    conda-forge
hdf4                      4.2.13            h10796ff_1004    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1112    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs-lite          2019.12.3        py36h92226af_3    conda-forge
imageio                   2.9.0                      py_0    conda-forge
imagesize                 1.2.0              pyhd3eb1b0_0  
immutables                0.14             py36h8c4c3a4_1    conda-forge
importlib-metadata        3.10.0           py36h06a4308_0  
importlib_metadata        3.10.0               hd8ed1ab_0    conda-forge
importlib_resources       5.2.2              pyhd8ed1ab_0    conda-forge
inflection                0.5.1            py36h06a4308_0  
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py36h5ca1d4c_0  
ipython                   7.16.1           py36h5ca1d4c_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
isort                     5.8.0              pyhd3eb1b0_0  
jasper                    1.900.1           h07fcdf6_1006    conda-forge
javabridge                1.0.18.post21+g4526f53          pypi_0    pypi
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.17.2           py36h06a4308_1  
jeepney                   0.6.0              pyhd3eb1b0_0  
jinja2                    2.11.3             pyhd3eb1b0_0  
jinja2-time               0.2.0              pyhd3eb1b0_2  
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
jsoncpp                   1.8.4             hc9558a2_1002    conda-forge
jsonschema                3.2.0                      py_2  
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_core              4.7.1            py36h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jxrlib                    1.1                  h7f98852_2    conda-forge
keyring                   22.3.0           py36h06a4308_0  
kiwisolver                1.3.1            py36h51d7077_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lame                      3.100             h14c3975_1001    conda-forge
lazy-object-proxy         1.6.0            py36h27cfd23_0  
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
lerc                      2.2                  h9c3ff4c_0    conda-forge
libaec                    1.0.4                h9c3ff4c_1    conda-forge
libblas                   3.9.0                3_openblas    conda-forge
libcblas                  3.9.0                3_openblas    conda-forge
libclang                  11.0.0          default_ha5c780c_2    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 11.2.0               h1d223b6_8    conda-forge
libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
libgfortran5              9.3.0               he4bcb1c_17    conda-forge
libglib                   2.66.4               h164308a_1    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libgomp                   11.2.0               h1d223b6_8    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                3_openblas    conda-forge
liblapacke                3.9.0                3_openblas    conda-forge
libllvm11                 11.0.0               he513fc3_0    conda-forge
libnetcdf                 4.7.4           nompi_h56d31a8_107    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libogg                    1.3.4                h7f98852_0    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libopencv                 4.5.1            py36h929e1cd_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     12.3                 h255efa7_3    conda-forge
libprotobuf               3.15.8               h780b84a_0    conda-forge
libsodium                 1.0.18               h7b6447c_0  
libspatialindex           1.9.3                h2531618_0  
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtheora                 1.1.1             h516909a_1004    conda-forge
libtiff                   4.3.0                hf544144_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                he1b5a44_0    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
loguru                    0.5.3            py36h9f0ad1d_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markupsafe                1.1.1            py36h7b6447c_0  
matplotlib                3.2.2                         1    conda-forge
matplotlib-base           3.2.2            py36h5fdd944_1    conda-forge
matplotlib-scalebar       0.7.2                    pypi_0    pypi
mayavi                    4.7.2            py36h5855d02_4    conda-forge
mccabe                    0.6.1                    py36_1  
mistune                   0.8.4            py36h7b6447c_0  
mypy_extensions           0.4.3                    py36_0  
mysql-common              8.0.25               ha770c72_2    conda-forge
mysql-libs                8.0.25               hfa10184_2    conda-forge
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7                    py36_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.5.1              pyhd3eb1b0_0  
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  2.5                        py_0    conda-forge
nibabel                   3.2.1                    pypi_0    pypi
nspr                      4.29                 he1b5a44_1    conda-forge
nss                       3.60                 hb5efdd6_0    conda-forge
numpy                     1.19.4           py36h2aa4a07_2    conda-forge
numpydoc                  1.1.0              pyhd3eb1b0_1  
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv                    4.5.1            py36h5fab9bb_1    conda-forge
openh264                  2.1.1                h8b12597_0    conda-forge
openjdk                   8.0.302              h7f98852_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
packaging                 20.9               pyhd3eb1b0_0  
pandas                    1.1.5            py36h284efc9_0    conda-forge
pandoc                    2.12                 h06a4308_0  
pandocfilters             1.4.3            py36h06a4308_1  
parso                     0.7.0                      py_0  
pathlib                   1.0.1            py36h5fab9bb_4    conda-forge
pathspec                  0.7.0                      py_0  
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.3.2            py36h676a545_0    conda-forge
pip                       21.3               pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pluggy                    0.13.1           py36h06a4308_0  
poyo                      0.5.0              pyhd3eb1b0_0  
proj                      7.1.1                h966b41f_3    conda-forge
prompt-toolkit            3.0.17             pyh06a4308_0  
psutil                    5.8.0            py36h27cfd23_1  
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2  
pugixml                   1.11.4               h9c3ff4c_0    conda-forge
py-opencv                 4.5.1            py36hcb3619a_1    conda-forge
pyamg                     4.1.0            py36h706143c_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pycodestyle               2.6.0              pyhd3eb1b0_0  
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydocstyle                6.0.0              pyhd3eb1b0_0  
pyface                    7.3.0              pyh44b312d_1    conda-forge
pyflakes                  2.2.0              pyhd3eb1b0_0  
pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
pylint                    2.7.4            py36h06a4308_1  
pyls-black                0.4.6                hd3eb1b0_0  
pyls-spyder               0.3.2              pyhd3eb1b0_0  
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py36h5fab9bb_6    conda-forge
pyqt-impl                 5.12.3           py36h7ec31b9_6    conda-forge
pyqt5-sip                 4.19.18          py36hc4f0c31_6    conda-forge
pyqtchart                 5.12             py36h7ec31b9_6    conda-forge
pyqtwebengine             5.12.1           py36h7ec31b9_6    conda-forge
pyrsistent                0.17.3           py36h7b6447c_0  
pysocks                   1.7.1            py36h9880bd3_2    conda-forge
python                    3.6.13          hffdb5ce_0_cpython    conda-forge
python-bioformats         1.1.0                    pypi_0    pypi
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.36.2             pyhd3eb1b0_0  
python-slugify            4.0.1                      py_0  
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1            py36h92226af_3    conda-forge
pyxdg                     0.27               pyhd3eb1b0_0  
pyyaml                    5.3.1            py36he6145b8_1    conda-forge
pyzmq                     20.0.0           py36h2531618_1  
qdarkstyle                3.0.2              pyhd3eb1b0_0  
qstylizer                 0.1.10             pyhd3eb1b0_0  
qt                        5.12.9               h763d07f_1    conda-forge
qtawesome                 1.0.2              pyhd3eb1b0_0  
qtconsole                 5.0.3              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  he28a2e2_2    conda-forge
regex                     2021.4.4         py36h27cfd23_0  
requests                  2.25.1             pyhd3eb1b0_0  
rope                      0.18.0                     py_0  
rsa                       4.4.1              pyh9f0ad1d_0    conda-forge
rtree                     0.9.7            py36h06a4308_1  
s3transfer                0.3.3              pyhd8ed1ab_5    conda-forge
scikit-image              0.17.2           py36h284efc9_4    conda-forge
scikit-learn              0.24.2           py36h2fdd933_1    conda-forge
scipy                     1.5.3            py36h9e8f40b_0    conda-forge
secretstorage             3.3.1            py36h06a4308_0  
setuptools                49.6.0           py36h9880bd3_2    conda-forge
simpleitk                 1.2.0rc2.dev1162+g2a79d          pypi_0    pypi
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
snowballstemmer           2.1.0              pyhd3eb1b0_0  
sortedcontainers          2.3.0              pyhd3eb1b0_0  
sphinx                    3.5.4              pyhd3eb1b0_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    1.0.3              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.4              pyhd3eb1b0_0  
spyder                    5.0.0            py36h06a4308_1  
spyder-kernels            2.0.1            py36h06a4308_0  
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tbb                       2020.2               h4bd325d_1    conda-forge
tbb-devel                 2020.2               h4bd325d_1    conda-forge
testpath                  0.4.4              pyhd3eb1b0_0  
text-unidecode            1.3                        py_0  
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
three-merge               0.1.1              pyhd3eb1b0_0  
tifffile                  2019.7.26.2              py36_0    conda-forge
tinycss                   0.4             pyhd3eb1b0_1002  
tk                        8.6.11               h27826a3_1    conda-forge
toml                      0.10.2             pyhd3eb1b0_0  
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py36h1d69622_0    conda-forge
tqdm                      4.62.1             pyhd3eb1b0_1  
traitlets                 4.3.3                    py36_0  
traits                    6.1.1            py36h1d69622_0    conda-forge
traitsui                  7.2.0              pyhd8ed1ab_0    conda-forge
typed-ast                 1.4.2            py36h27cfd23_1  
typing_extensions         3.7.4.3            pyha847dfd_0  
ujson                     4.0.2            py36h2531618_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
utfcpp                    3.1.2                         0    conda-forge
vtk                       9.0.1           no_osmesa_py36hdc5cf2b_103    conda-forge
watchdog                  1.0.2            py36h06a4308_1  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py36_1  
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
whichcraft                0.6.1              pyhd3eb1b0_0  
wrapt                     1.12.1           py36h7b6447c_1  
wurlitzer                 2.1.0            py36h06a4308_0  
x264                      1!152.20180806       h14c3975_0    conda-forge
xlrd                      1.2.0                    py36_0    anaconda
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.2.0                h516909a_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yapf                      0.31.0             pyhd3eb1b0_0  
zeromq                    4.3.4                h2531618_0  
zfp                       0.5.5                h9c3ff4c_4    conda-forge
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge

```

**Comment by yoda-vid** [comment]
Great, glad it worked!

Thanks for the Conda info. Good to know this other error doesn't appear to be an issue here but let me know if it causes any problems.
